#!/usr/bin/env python3
"""Setup helper to pre-download preset songs into the local song library."""

import time

from app import scraper, storage

PRESET_QUERIES = [
    "Nirvana Smells Like Teen Spirit",
    "Queen Bohemian Rhapsody",
    "Oasis Wonderwall",
    "Metallica Enter Sandman",
    "The Beatles Hey Jude",
    "Guns N' Roses Sweet Child O' Mine",
    "Led Zeppelin Stairway to Heaven",
    "AC/DC Back in Black",
    "Pink Floyd Wish You Were Here",
    "Red Hot Chili Peppers Under the Bridge",
    "Green Day American Idiot",
    "Arctic Monkeys Do I Wanna Know",
    "The Killers Mr Brightside",
    "Coldplay Yellow",
    "U2 With or Without You",
    "Bon Jovi Livin on a Prayer",
    "Foo Fighters Everlong",
    "The Rolling Stones Paint It Black",
    "David Bowie Heroes",
    "Blur Song 2",
    "Radiohead Creep",
    "The Police Every Breath You Take",
    "Eagles Hotel California",
    "Journey Dont Stop Believin",
    "Bruce Springsteen Born to Run",
    "The Who Baba ORiley",
    "The Clash London Calling",
    "Paramore Misery Business",
    "Linkin Park In the End",
    "Muse Starlight",
    "Kings of Leon Sex on Fire",
    "The White Stripes Seven Nation Army",
    "Franz Ferdinand Take Me Out",
    "The Strokes Last Nite",
    "Weezer Buddy Holly",
    "My Chemical Romance Welcome to the Black Parade",
    "Fall Out Boy Sugar Were Goin Down",
    "Panic At The Disco I Write Sins Not Tragedies",
    "Blink 182 All the Small Things",
    "Sum 41 Fat Lip",
    "Avril Lavigne Complicated",
    "The Cranberries Zombie",
    "Snow Patrol Chasing Cars",
    "Keane Somewhere Only We Know",
    "Travis Why Does It Always Rain on Me",
    "Stereophonics Dakota",
    "Kasabian Fire",
    "The Verve Bitter Sweet Symphony",
    "Placebo Every You Every Me",
    "Manic Street Preachers If You Tolerate This",
    "The Libertines Dont Look Back Into the Sun",
    "The 1975 Chocolate",
    "Sam Fender Seventeen Going Under",
    "George Ezra Budapest",
    "Ed Sheeran Thinking Out Loud",
    "Lewis Capaldi Someone You Loved",
    "Adele Rolling in the Deep",
    "Amy Winehouse Valerie",
    "Norah Jones Dont Know Why",
    "John Mayer Slow Dancing in a Burning Room",
    "Eric Clapton Tears in Heaven",
    "Jimi Hendrix Purple Haze",
    "Jimi Hendrix Hey Joe",
    "Cream Sunshine of Your Love",
    "Dire Straits Sultans of Swing",
    "Fleetwood Mac Go Your Own Way",
    "Fleetwood Mac Dreams",
    "Bob Dylan Knockin on Heavens Door",
    "Bob Marley No Woman No Cry",
    "The Beach Boys Good Vibrations",
    "Simon and Garfunkel The Sound of Silence",
    "Johnny Cash Hurt",
    "Elvis Presley Cant Help Falling in Love",
    "Chuck Berry Johnny B Goode",
    "Buddy Holly Peggy Sue",
    "The Kinks You Really Got Me",
    "The Doors Light My Fire",
    "The Doors Riders on the Storm",
    "Stevie Wonder Superstition",
    "Prince Purple Rain",
    "Michael Jackson Beat It",
    "Michael Jackson Billie Jean",
    "Whitney Houston I Wanna Dance with Somebody",
    "Cyndi Lauper Girls Just Want to Have Fun",
    "Toto Africa",
    "Aha Take On Me",
    "Rick Astley Never Gonna Give You Up",
    "Duran Duran Hungry Like the Wolf",
    "Spandau Ballet True",
    "Simple Minds Dont You Forget About Me",
    "Soft Cell Tainted Love",
    "Depeche Mode Enjoy the Silence",
    "The Cure Just Like Heaven",
    "The Smiths There Is a Light That Never Goes Out",
    "Joy Division Love Will Tear Us Apart",
    "New Order Blue Monday",
    "Talking Heads Psycho Killer",
    "Blondie Heart of Glass",
    "The Pretenders Brass in Pocket",
    "Alanis Morissette Ironic",
    "Sheryl Crow All I Wanna Do",
    "Natalie Imbruglia Torn",
    "No Doubt Dont Speak",
    "Garbage Stupid Girl",
    "Hole Celebrity Skin",
    "Soundgarden Black Hole Sun",
    "Pearl Jam Alive",
    "Alice in Chains Man in the Box",
    "Stone Temple Pilots Plush",
    "Rage Against the Machine Killing in the Name",
    "System of a Down Chop Suey",
    "Slipknot Duality",
    "Korn Freak on a Leash",
    "Bring Me The Horizon Drown",
    "Twenty One Pilots Stressed Out",
    "Imagine Dragons Radioactive",
    "OneRepublic Counting Stars",
    "Maroon 5 She Will Be Loved",
    "Bruno Mars Locked Out of Heaven",
    "Justin Timberlake Cry Me a River",
    "Harry Styles As It Was",
    "Taylor Swift Love Story",
    "Olivia Rodrigo Drivers License",
    "Billie Eilish Bad Guy",
    "Lana Del Rey Video Games",
    "Hozier Take Me to Church",
    "Vance Joy Riptide",
    "Passenger Let Her Go",
    "Jason Mraz Im Yours",
    "Train Hey Soul Sister",
    "Plain White Ts Hey There Delilah",
    "The Lumineers Ho Hey",
    "Mumford and Sons Little Lion Man",
    "Of Monsters and Men Little Talks",
    "The Script Breakeven",
    "Bastille Pompeii",
    "Walk the Moon Shut Up and Dance",
    "Foster the People Pumped Up Kicks",
    "MGMT Kids",
    "Alt J Breezeblocks",
    "Glass Animals Heat Waves",
    "Tame Impala The Less I Know the Better",
    "Gorillaz Feel Good Inc",
    "Daft Punk Get Lucky",
    "Calvin Harris Summer",
    "Avicii Wake Me Up",
    "Swedish House Mafia Dont You Worry Child",
    "David Guetta Titanium",
    "Zedd Clarity",
    "Kygo Firestone",
    "ODESZA Say My Name",
    "Disclosure Latch",
    "The Weeknd Blinding Lights",
    "Drake Hotline Bling",
    "Post Malone Circles",
    "Kanye West Stronger",
    "Jay Z Empire State of Mind",
    "Eminem Lose Yourself",
    "50 Cent In Da Club",
    "Outkast Hey Ya",
    "Childish Gambino Redbone",
    "Frank Ocean Thinkin Bout You",
    "SZA Kill Bill",
    "Doja Cat Say So",
    "Dua Lipa Levitating",
    "Lady Gaga Poker Face",
    "Katy Perry Firework",
    "Rihanna Umbrella",
    "Beyonce Halo",
    "Shakira Hips Dont Lie",
    "Pitbull Give Me Everything",
    "Enrique Iglesias Bailando",
    "Luis Fonsi Despacito",
    "Bad Bunny Tití Me Preguntó",
    "Karol G Tusa",
    "Rosalia Malamente",
    "Coldplay Viva La Vida",
    "Snow Patrol Run",
    "Keane Everybody's Changing",
    "The Fray How to Save a Life",
    "Goo Goo Dolls Iris",
    "Lifehouse Hanging by a Moment",
    "Matchbox Twenty Unwell",
    "Counting Crows Mr Jones",
    "Semisonic Closing Time",
    "Third Eye Blind Semi Charmed Life",
    "Smash Mouth All Star",
    "Spin Doctors Two Princes",
    "Hootie and the Blowfish Only Wanna Be with You",
    "Train Drops of Jupiter",
    "John Denver Take Me Home Country Roads",
    "Eagles Take It Easy",
    "America A Horse with No Name",
    "Creedence Clearwater Revival Bad Moon Rising",
    "Lynyrd Skynyrd Sweet Home Alabama",
    "ZZ Top La Grange",
    "Deep Purple Smoke on the Water",
    "Black Sabbath Paranoid",
    "Iron Maiden The Trooper",
    "Judas Priest Breaking the Law",
    "Megadeth Symphony of Destruction",
    "Pantera Walk",
    "Slayer Raining Blood",
    "Motorhead Ace of Spades",
    "Thin Lizzy The Boys Are Back in Town",
    "The Jam Town Called Malice",
    "Paul Weller You Do Something to Me",
    "Elton John Rocket Man",
    "Billy Joel Piano Man",
    "Phil Collins In the Air Tonight",
    "Genesis Invisible Touch",
    "Peter Gabriel Sledgehammer",
    "Kate Bush Running Up That Hill",
    "Annie Lennox Walking on Broken Glass",
    "Eurythmics Sweet Dreams",
    "Tears for Fears Everybody Wants to Rule the World",
    "Hall and Oates You Make My Dreams",
    "Earth Wind and Fire September",
    "Bee Gees Stayin Alive",
    "ABBA Dancing Queen",
    "Boney M Rasputin",
    "Modern Talking Cheri Cheri Lady",
    "Wham Wake Me Up Before You Go Go",
    "George Michael Faith",
    "Rod Stewart Maggie May",
    "Bryan Adams Summer of 69",
    "Simple Plan Perfect",
    "Good Charlotte The Anthem",
    "All Time Low Dear Maria Count Me In",
    "Paramore Still Into You",
    "The Offspring Self Esteem",
    "Jimmy Eat World The Middle",
    "Dashboard Confessional Hands Down",
    "Death Cab for Cutie I Will Follow You into the Dark",
    "Bright Eyes First Day of My Life",
    "Bon Iver Skinny Love",
    "Phoebe Bridgers Motion Sickness",
    "Clairo Sofia",
    "Beabadoobee Coffee",
]


def predownload_presets():
    config = storage.load_config()
    default_zoom = config.get("default_zoom", 3)

    for query in PRESET_QUERIES:
        print(f"Searching for preset: {query}")
        results, err = scraper.search_ultimate_guitar(query)
        if err or not results:
            print(f"  Skipped: {err or 'no results'}")
            continue

        chosen = results[0]
        print(f"  Downloading: {chosen['artist']} - {chosen['song']}")
        content, err = scraper.fetch_tab_content(chosen['url'])
        if err or not content:
            print(f"  Failed: {err or 'empty content'}")
            continue

        folder, version = storage.save_song(
            f"{chosen['artist']} - {chosen['song']}",
            content,
            artist=chosen['artist'],
            default_zoom=default_zoom,
        )
        print(f"  Saved: {folder}/{version}\n")
        time.sleep(2)

    print("Preset download complete.")


if __name__ == "__main__":
    predownload_presets()
